FROM python:3.11-slim

RUN apt-get update 

RUN apt-get install -y \
        ffmpeg \
        nano \
        curl

RUN pip install --upgrade pip

WORKDIR /briefcam
COPY requirements.txt /briefcam/requirements.txt

RUN python3 -m pip --no-cache-dir install protobuf==3.20.*
RUN python3 -m pip --no-cache-dir install --ignore-installed -r /briefcam/requirements.txt

COPY ./src /briefcam

ENV REDISTOGO_URL=redis://171.244.5.181:6380
ENV URL_ACCESS=""
ENV FOLDER_STORAGE=storage

# CMD ["python3", "controller.py"]

# docker build -t mq/briefcam --load --rm -f Dockerfile_briefcam .
# docker run -d -p 3456:3456 --gpus all --name briefcam mq/briefcam
# docker run -d -p 3456:3456 -v %cd%/src/weights:/briefcam/weights --name briefcam mq/briefcam

# export REDISTOGO_URL=redis://192.168.6.159:6380