FROM nvidia/cuda:12.0.1-base-ubuntu20.04
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Ho_Chi_Minh

RUN apt-get update && \
	apt-get install -y python3.10 && \
	apt-get install -y \
			python3-pip \
			python3-dev \
			ffmpeg \
			nano \
			curl

RUN python3 -m pip install --upgrade pip

WORKDIR /briefcam
COPY requirements.txt /briefcam/requirements.txt

RUN python3 -m pip --no-cache-dir install protobuf==3.20.*

RUN python3 -m pip --no-cache-dir install --ignore-installed -r /briefcam/requirements.txt

COPY ./src /briefcam

ENV REDISTOGO_URL=redis://192.168.6.159:6380

# CMD ["python3", "controller.py"]

# docker build -t mq/briefcam --load --rm -f Dockerfile_controller .
# docker run -d -p 3456:3456 --gpus all --name briefcam mq/briefcam
# docker run -d -p 3456:3456 -v %cd%/src/weights:/briefcam/weights --name briefcam mq/briefcam

# export REDISTOGO_URL=redis://192.168.6.159:6380